services:
  backend:
    image: mysite-backend
    pull_policy: never
    container_name: mysite-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    # tells which other service needs to be started first, for example our backend needs the database to start up before
    depends_on:
      - mongodb
  
  frontend:
    image: mysite-frontend
    pull_policy: never
    container_name: mysite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
  mongodb:
    image: mongo:8.2.5
    container_name: mysite-mongodb
    volumes:
      - mongodb-data:/data/db
    # unsafe way to pass the variables (docker-compose is tracked on git)
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: pass1
    # instead, do this for now:
    env_file:
      - ./mongodb/.env
    # if you need even more security then need to use a secrets manager like azure vault or docker swarm mode for docker secrets manager
  
  # to easily explore db, during dev, add mongoexpress
  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    container_name: mysite-mongo-express
    env_file:
      - ./mongo-express/.env
volumes:
  mongodb-data: {}